version: "3.9"
services:
  client:
    container_name: product-page-client
    image: product-page/client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: deploy
    depends_on:
      - server
    ports:
      - "8080:80"
    networks:
      - app-network

  server:
    container_name: product-page-server
    image: product-page/server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - PORT=3000

networks:
  app-network:
    driver: bridge